export const mockProfiles = [
  {
    id: '1',
    name: 'Sarah Chen',
    imageUrl: 'https://randomuser.me/api/portraits/women/1.jpg',
    groupName: 'Design Masters',
    bio: 'UI/UX designer passionate about creating beautiful user experiences',
    tags: ['Designer', 'Prototyping', 'User Research'],
    isOnline: true,
    seekingGroup: false,
    achievements: ['Group Creator', 'Design Expert'],
    location: 'San Francisco',
    lastActive: '2024-03-15T10:30:00Z'
  },
  {
    id: '2',
    name: 'Marcus Johnson',
    imageUrl: 'https://randomuser.me/api/portraits/men/1.jpg',
    bio: 'Full-stack developer looking for an innovative team',
    tags: ['Coder', 'React', 'Node.js'],
    isOnline: true,
    seekingGroup: true,
    achievements: ['Code Ninja'],
    location: 'New York',
    lastActive: '2024-03-15T09:45:00Z'
  },
  {
    id: '3',
    name: 'Emma Wilson',
    imageUrl: 'https://randomuser.me/api/portraits/women/2.jpg',
    groupName: 'Tech Innovators',
    bio: 'Product Manager with 5 years of experience in tech',
    tags: ['Product', 'Strategy', 'Leadership'],
    isOnline: false,
    seekingGroup: false,
    achievements: ['Team Leader', 'Product Guru'],
    location: 'London',
    lastActive: '2024-03-14T18:20:00Z'
  },
  {
    id: '4',
    name: 'John Doe',
    imageUrl: 'https://randomuser.me/api/portraits/men/2.jpg',
    groupName: 'Frontend Wizards',
    bio: 'JavaScript enthusiast and frontend developer',
    tags: ['Frontend', 'JavaScript', 'CSS'],
    isOnline: true,
    seekingGroup: false,
    achievements: ['Frontend Expert'],
    location: 'Berlin',
    lastActive: '2024-03-15T11:00:00Z'
  },
  {
    id: '5',
    name: 'Alice Green',
    imageUrl: 'https://randomuser.me/api/portraits/women/3.jpg',
    bio: 'Graphic designer and illustrator with a love for creativity',
    tags: ['Graphics', 'Illustration', 'Branding'],
    isOnline: false,
    seekingGroup: true,
    achievements: ['Creative Visionary'],
    location: 'Los Angeles',
    lastActive: '2024-03-14T17:30:00Z'
  },
  {
    id: '6',
    name: 'Lucas Martinez',
    imageUrl: 'https://randomuser.me/api/portraits/men/3.jpg',
    groupName: 'Machine Learning Masters',
    bio: 'AI and Machine Learning expert, building smarter systems',
    tags: ['AI', 'Python', 'Machine Learning'],
    isOnline: true,
    seekingGroup: false,
    achievements: ['AI Innovator'],
    location: 'Barcelona',
    lastActive: '2024-03-15T08:15:00Z'
  },
  {
    id: '7',
    name: 'Sophia Davis',
    imageUrl: 'https://randomuser.me/api/portraits/women/4.jpg',
    bio: 'Marketing professional passionate about digital strategies',
    tags: ['Marketing', 'SEO', 'Brand Strategy'],
    isOnline: true,
    seekingGroup: true,
    achievements: ['Marketing Strategist'],
    location: 'Sydney',
    lastActive: '2024-03-15T10:00:00Z'
  },
  {
    id: '8',
    name: 'James Smith',
    imageUrl: 'https://randomuser.me/api/portraits/men/4.jpg',
    groupName: 'Fullstack Devs',
    bio: 'Experienced full-stack developer, constantly learning',
    tags: ['Fullstack', 'Node.js', 'GraphQL'],
    isOnline: false,
    seekingGroup: false,
    achievements: ['Tech Lead'],
    location: 'Toronto',
    lastActive: '2024-03-13T20:45:00Z'
  },
  {
    id: '9',
    name: 'Olivia White',
    imageUrl: 'https://randomuser.me/api/portraits/women/5.jpg',
    bio: 'Content strategist with a flair for storytelling',
    tags: ['Content', 'Writing', 'SEO'],
    isOnline: true,
    seekingGroup: false,
    achievements: ['Content King'],
    location: 'Vancouver',
    lastActive: '2024-03-15T07:00:00Z'
  },
  {
    id: '10',
    name: 'Liam Brown',
    imageUrl: 'https://randomuser.me/api/portraits/men/5.jpg',
    groupName: 'Cybersecurity Experts',
    bio: 'Cybersecurity consultant focused on threat mitigation',
    tags: ['Security', 'Ethical Hacking', 'Network'],
    isOnline: false,
    seekingGroup: true,
    achievements: ['Hacker Pro'],
    location: 'Chicago',
    lastActive: '2024-03-14T22:15:00Z'
  },
  {
    id: '11',
    name: 'Charlotte Harris',
    imageUrl: 'https://randomuser.me/api/portraits/women/6.jpg',
    bio: 'Front-end developer with a passion for user-centered design',
    tags: ['HTML', 'CSS', 'UI Design'],
    isOnline: true,
    seekingGroup: false,
    achievements: ['Web Developer'],
    location: 'Paris',
    lastActive: '2024-03-15T09:30:00Z'
  },
  {
    id: '12',
    name: 'Ethan Taylor',
    imageUrl: 'https://randomuser.me/api/portraits/men/6.jpg',
    bio: 'Data scientist and analytics expert working with large data sets',
    tags: ['Data Science', 'Python', 'Machine Learning'],
    isOnline: false,
    seekingGroup: true,
    achievements: ['Data Expert'],
    location: 'Berlin',
    lastActive: '2024-03-13T19:00:00Z'
  },
  {
    id: '13',
    name: 'Amelia Lee',
    imageUrl: 'https://randomuser.me/api/portraits/women/7.jpg',
    bio: 'Brand designer focusing on elevating brand identity',
    tags: ['Branding', 'Design', 'Strategy'],
    isOnline: true,
    seekingGroup: false,
    achievements: ['Brand Guru'],
    location: 'San Francisco',
    lastActive: '2024-03-15T06:00:00Z'
  },
  {
    id: '14',
    name: 'Benjamin Clark',
    imageUrl: 'https://randomuser.me/api/portraits/men/7.jpg',
    bio: 'Digital artist creating beautiful visuals for games',
    tags: ['Art', 'Games', 'Illustration'],
    isOnline: true,
    seekingGroup: true,
    achievements: ['Digital Art Master'],
    location: 'Los Angeles',
    lastActive: '2024-03-15T11:30:00Z'
  },
  {
    id: '15',
    name: 'Ella Young',
    imageUrl: 'https://randomuser.me/api/portraits/women/8.jpg',
    bio: 'Software engineer with expertise in backend systems',
    tags: ['Backend', 'API', 'Java'],
    isOnline: true,
    seekingGroup: false,
    achievements: ['Backend Engineer'],
    location: 'New York',
    lastActive: '2024-03-15T09:30:00Z'
  },
  {
    id: '16',
    name: 'Aiden Scott',
    imageUrl: 'https://randomuser.me/api/portraits/men/8.jpg',
    bio: 'Cloud architect with a focus on scalable systems',
    tags: ['Cloud', 'AWS', 'Architecture'],
    isOnline: true,
    seekingGroup: true,
    achievements: ['Cloud Expert'],
    location: 'Austin',
    lastActive: '2024-03-15T12:00:00Z'
  },
  {
    id: '17',
    name: 'Mia Robinson',
    imageUrl: 'https://randomuser.me/api/portraits/women/9.jpg',
    bio: 'Data analyst with a passion for extracting insights from data',
    tags: ['Data', 'Analysis', 'SQL'],
    isOnline: false,
    seekingGroup: false,
    achievements: ['Data Analyst'],
    location: 'Miami',
    lastActive: '2024-03-14T20:30:00Z'
  },
  {
    id: '18',
    name: 'Oliver King',
    imageUrl: 'https://randomuser.me/api/portraits/men/9.jpg',
    bio: 'Digital marketer with a focus on social media growth',
    tags: ['Marketing', 'Social Media', 'Strategy'],
    isOnline: false,
    seekingGroup: true,
    achievements: ['Social Media Expert'],
    location: 'London',
    lastActive: '2024-03-14T18:45:00Z'
  },
  {
    id: '19',
    name: 'Isabella Adams',
    imageUrl: 'https://randomuser.me/api/portraits/women/10.jpg',
    bio: 'Creative coder with a passion for web development',
    tags: ['Web Development', 'CSS', 'JavaScript'],
    isOnline: true,
    seekingGroup: false,
    achievements: ['Creative Coder'],
    location: 'Tokyo',
    lastActive: '2024-03-15T10:15:00Z'
  },
  {
    id: '20',
    name: 'Sebastian Lopez',
    imageUrl: 'https://randomuser.me/api/portraits/men/10.jpg',
    bio: 'Experienced project manager, passionate about leading teams',
    tags: ['Project Management', 'Agile', 'Scrum'],
    isOnline: false,
    seekingGroup: true,
    achievements: ['Agile Leader'],
    location: 'Paris',
    lastActive: '2024-03-13T17:00:00Z'
  },
  {
    id: '21',
    name: 'Harper Davis',
    imageUrl: 'https://randomuser.me/api/portraits/women/11.jpg',
    bio: 'Frontend developer with a love for UI/UX design',
    tags: ['HTML', 'CSS', 'UX Design'],
    isOnline: true,
    seekingGroup: false,
    achievements: ['Frontend Developer'],
    location: 'Berlin',
    lastActive: '2024-03-15T11:45:00Z'
  },
  {
    id: '22',
    name: 'Jack Moore',
    imageUrl: 'https://randomuser.me/api/portraits/men/11.jpg',
    bio: 'SEO expert helping businesses grow online',
    tags: ['SEO', 'Marketing', 'Content Strategy'],
    isOnline: true,
    seekingGroup: false,
    achievements: ['SEO Specialist'],
    location: 'Toronto',
    lastActive: '2024-03-15T10:45:00Z'
  },
  {
    id: '23',
    name: 'Zoe Taylor',
    imageUrl: 'https://randomuser.me/api/portraits/women/12.jpg',
    bio: 'Game developer with a focus on AR and VR experiences',
    tags: ['Game Development', 'AR', 'VR'],
    isOnline: false,
    seekingGroup: true,
    achievements: ['AR/VR Innovator'],
    location: 'San Francisco',
    lastActive: '2024-03-13T21:00:00Z'
  },
  {
    id: '24',
    name: 'Mason Johnson',
    imageUrl: 'https://randomuser.me/api/portraits/men/12.jpg',
    bio: 'Back-end engineer focused on API design',
    tags: ['Backend', 'API', 'Python'],
    isOnline: true,
    seekingGroup: false,
    achievements: ['API Expert'],
    location: 'Dallas',
    lastActive: '2024-03-15T08:30:00Z'
  },
  {
    id: '25',
    name: 'Chloe White',
    imageUrl: 'https://randomuser.me/api/portraits/women/13.jpg',
    bio: 'Software engineer with a focus on mobile app development',
    tags: ['Mobile', 'iOS', 'Swift'],
    isOnline: false,
    seekingGroup: false,
    achievements: ['Mobile Developer'],
    location: 'Chicago',
    lastActive: '2024-03-14T23:00:00Z'
  }
];
